import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SiteFooter from "@/components/layout/SiteFooter";
import UserContextProvider from "@/store/UserContext";
import { getUserFromCookies } from "@/lib/session";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = (await getUserFromCookies()) || {
    username: "",
    jobTitle: "",
  };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserContextProvider value={user}>
          <div className="site flex min-h-screen flex-col items-center justify-center">
            {children}
            <SiteFooter />
          </div>
        </UserContextProvider>
      </body>
    </html>
  );
}
